import type { MenuData } from './types';

export const MENU: MenuData = {
  'Veg Soup': [
    { n: 'Corn Soup', p: 80 },
    { n: 'Manchow Soup', p: 80 },
    { n: 'Hot & Sour Soup', p: 80 },
  ],
  'Non-Veg Soup': [
    { n: 'Chicken Corn Soup', p: 95 },
    { n: 'Chicken Manchow', p: 95 },
    { n: 'Chicken Hot & Sour', p: 95 },
  ],
  'Egg Starters': [
    { n: 'Egg 65', p: 180 },
    { n: 'Egg Manchuria', p: 180 },
    { n: 'Egg Burgi', p: 100 },
    { n: 'Chilli Egg', p: 180 },
    { n: 'Egg Omelette', p: 70 },
  ],
  'Veg Starters': [
    { n: 'Veg Manchuria', p: 170 },
    { n: 'Gobi Manchuria', p: 170 },
    { n: 'Gobi 65', p: 170 },
    { n: 'Paneer 65', p: 220 },
    { n: 'Paneer Manchuria', p: 220 },
    { n: 'Chilli Paneer', p: 210 },
    { n: 'Baby Corn 65', p: 180 },
  ],
  'Chicken Starters': [
    { n: 'Chicken 65', p: 220 },
    { n: 'Pepper Chicken', p: 240 },
    { n: 'Chilli Chicken', p: 220 },
    { n: 'Chicken Fry', p: 240 },
    { n: 'Chicken 777', p: 240 },
    { n: 'Chilli Drumsticks', p: 240 },
    { n: 'Chicken Manchuria', p: 240 },
    { n: 'Chicken Lollipop', p: 250 },
    { n: 'Crispy Chicken', p: 240 },
  ],
  'Sea Food Starters': [
    { n: 'Appollo Fish', p: 270 },
    { n: 'Chilli Fish', p: 270 },
    { n: 'Chilli Prawns', p: 280 },
    { n: 'Lemon Fish', p: 270 },
    { n: 'Prawns 65', p: 280 },
  ],
  'Tandoori': [
    { n: 'Tandoori Chicken Half', p: 200 },
    { n: 'Tandoori Chicken Full', p: 400 },
    { n: 'Tangdi Kabab', p: 300 },
    { n: 'Paneer Tikka', p: 260 },
  ],
  'Chinese Veg': [
    { n: 'Veg Soft Noodles', p: 160 },
    { n: 'Veg Fried Rice', p: 160 },
    { n: 'Schezwan Fried Rice', p: 180 },
    { n: 'Schezwan Noodles', p: 180 },
  ],
  'Chinese Non-Veg': [
    { n: 'Egg Soft Noodles', p: 170 },
    { n: 'Chicken Soft Noodles', p: 190 },
    { n: 'Chicken Schezwan Noodles', p: 200 },
    { n: 'Chicken Fried Rice', p: 190 },
  ],
  'Veg Curries': [
    { n: 'Dal Fry', p: 160 },
    { n: 'Paneer Do Pyaza', p: 230 },
    { n: 'Paneer Butter Masala', p: 230 },
    { n: 'Baby Corn Mushroom', p: 230 },
    { n: 'Veg Kolhapuri', p: 200 },
    { n: 'Kadai Paneer', p: 230 },
    { n: 'Aloo Mutter', p: 180 },
  ],
  'Chicken Curries': [
    { n: 'Chicken Curry', p: 230 },
    { n: 'Butter Chicken', p: 230 },
    { n: 'Kadai Chicken', p: 230 },
    { n: 'Chicken Kolhapuri', p: 250 },
    { n: 'Murg Musallam', p: 450 },
  ],
  'Mutton Curries': [
    { n: 'Mutton Masala', p: 320 },
    { n: 'Mutton Curry', p: 320 },
  ],
  'Sea Food Curries': [
    { n: 'Fish Curry', p: 280 },
    { n: 'Fish Masala', p: 280 },
    { n: 'Prawns Curry', p: 280 },
  ],
  'Bread': [
    { n: 'Phulka', p: 20 },
    { n: 'Chapathi', p: 25 },
    { n: 'Tandoor Roti', p: 30 },
    { n: 'Butter Naan', p: 40 },
    { n: 'Garlic Naan', p: 50 },
    { n: 'Aloo Paratha', p: 80 },
  ],
  'Rice': [
    { n: 'Plain Rice', p: 80 },
    { n: 'Lemon Rice', p: 120 },
    { n: 'Tomato Rice', p: 140 },
    { n: 'Zeera Rice', p: 120 },
  ],
  'Veg Biryanis': [
    { n: 'Veg Biryani', p: 170 },
    { n: 'Kaju Biryani', p: 200 },
    { n: 'Paneer Biryani', p: 200 },
    { n: 'Veg Biryani Full', p: 200 },
  ],
  'Non-Veg Biryanis': [
    { n: 'Chicken Biryani Half', p: 220 },
    { n: 'Chicken Biryani Full', p: 250 },
    { n: 'Gongura Chicken Biryani', p: 250 },
    { n: 'Mutton Biryani', p: 300 },
    { n: 'Fish Biryani', p: 280 },
    { n: 'Prawns Biryani', p: 280 },
  ],
  'Family Packs': [
    { n: 'Chicken Dum Family Pack', p: 600 },
    { n: 'Veg Family Pack', p: 400 },
    { n: 'Chicken Jumbo', p: 700 },
    { n: 'Mutton Jumbo', p: 800 },
  ],
  'Beverages': [
    { n: 'Water Bottle', p: 20 },
    { n: 'Soft Drink', p: 20 },
    { n: 'Lassi', p: 50 },
    { n: 'Fresh Lime Soda', p: 50 },
  ],
};
